-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 00:57:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydbrentacar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydbrentacar` ;

-- -----------------------------------------------------
-- Schema mydbrentacar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbrentacar` DEFAULT CHARACTER SET utf8 ;
USE `mydbrentacar` ;

-- -----------------------------------------------------
-- Table `mydbrentacar`.`Korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Korisnik` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Korisnik` (
  `sifra_korisnika` INT NOT NULL,
  `brVozackeDozvole` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sifra_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Pravno_Lice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Pravno_Lice` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Pravno_Lice` (
  `sifra_korisnika` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `PIB` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`sifra_korisnika`),
  INDEX `fk_Pravno_Lice_Korisnik_idx` (`sifra_korisnika` ASC),
  CONSTRAINT `fk_Pravno_Lice_Korisnik`
    FOREIGN KEY (`sifra_korisnika`)
    REFERENCES `mydbrentacar`.`Korisnik` (`sifra_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Fizicko_Lice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Fizicko_Lice` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Fizicko_Lice` (
  `sifra_korisnika` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `jmbg` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`sifra_korisnika`),
  INDEX `fk_Fizicko_Lice_Korisnik1_idx` (`sifra_korisnika` ASC),
  CONSTRAINT `fk_Fizicko_Lice_Korisnik1`
    FOREIGN KEY (`sifra_korisnika`)
    REFERENCES `mydbrentacar`.`Korisnik` (`sifra_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Lokacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Lokacija` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Lokacija` (
  `sifra_lokacije` INT NOT NULL,
  `telefon` VARCHAR(10) NOT NULL,
  `ptt` VARCHAR(6) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sifra_lokacije`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Vozilo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Vozilo` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Vozilo` (
  `brRegTablica` VARCHAR(10) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `godina_proizvodnje` YEAR NOT NULL,
  `boja` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'na stanju',
  `kapacitet` INT NULL,
  `tip` VARCHAR(45) NOT NULL,
  `cena_po_danu` FLOAT(10,2) NOT NULL,
  `sifra_lokacije` INT NOT NULL,
  PRIMARY KEY (`brRegTablica`),
  INDEX `fk_Vozilo_Lokacija1_idx` (`sifra_lokacije` ASC),
  CONSTRAINT `fk_Vozilo_Lokacija1`
    FOREIGN KEY (`sifra_lokacije`)
    REFERENCES `mydbrentacar`.`Lokacija` (`sifra_lokacije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Nacin_Placanja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Nacin_Placanja` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Nacin_Placanja` (
  `sifra_nacina_placanja` INT NOT NULL,
  `metod` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sifra_nacina_placanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Placanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Placanje` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Placanje` (
  `sifra_placanja` INT NOT NULL,
  `konacna_cena` FLOAT(10,2) NULL,
  `krajnji_datum` DATE NULL,
  `datum_placanja` DATE NULL,
  `popust` INT NULL,
  `sifra_nacina_placanja` INT NOT NULL,
  PRIMARY KEY (`sifra_placanja`),
  INDEX `fk_Placanje_Nacin_Placanja1_idx` (`sifra_nacina_placanja` ASC),
  CONSTRAINT `fk_Placanje_Nacin_Placanja1`
    FOREIGN KEY (`sifra_nacina_placanja`)
    REFERENCES `mydbrentacar`.`Nacin_Placanja` (`sifra_nacina_placanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Rentira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Rentira` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Rentira` (
  `sifra_korisnika` INT NOT NULL,
  `brRegTablica` VARCHAR(10) NOT NULL,
  `datum_pocetka` DATE NOT NULL,
  `datum_kraja` DATE NOT NULL,
  `datum_vracanja` DATE NULL,
  `ukupna_cena` FLOAT(10,2) NULL DEFAULT 0.00,
  `kazna` FLOAT(10,2) NULL,
  `sifra_lokacija` INT NULL,
  `sifra_placanja` INT NOT NULL,
  PRIMARY KEY (`sifra_korisnika`, `brRegTablica`),
  INDEX `fk_Korisnik_has_Vozilo_Vozilo1_idx` (`brRegTablica` ASC),
  INDEX `fk_Korisnik_has_Vozilo_Korisnik1_idx` (`sifra_korisnika` ASC),
  INDEX `fk_Rentira_Lokacija1_idx` (`sifra_lokacija` ASC),
  INDEX `fk_Rentira_Placanje1_idx` (`sifra_placanja` ASC),
  CONSTRAINT `fk_Korisnik_has_Vozilo_Korisnik1`
    FOREIGN KEY (`sifra_korisnika`)
    REFERENCES `mydbrentacar`.`Korisnik` (`sifra_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korisnik_has_Vozilo_Vozilo1`
    FOREIGN KEY (`brRegTablica`)
    REFERENCES `mydbrentacar`.`Vozilo` (`brRegTablica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rentira_Lokacija1`
    FOREIGN KEY (`sifra_lokacija`)
    REFERENCES `mydbrentacar`.`Lokacija` (`sifra_lokacije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rentira_Placanje1`
    FOREIGN KEY (`sifra_placanja`)
    REFERENCES `mydbrentacar`.`Placanje` (`sifra_placanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Osiguranje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Osiguranje` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Osiguranje` (
  `sifra_osiguranja` INT NOT NULL,
  `pokrice_korisnika` FLOAT(10,2) NOT NULL,
  `pokrice_sl_stete` FLOAT(10,2) NOT NULL,
  `tip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sifra_osiguranja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Poseduje_Osiguranje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Poseduje_Osiguranje` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Poseduje_Osiguranje` (
  `brRegTablica` VARCHAR(10) NOT NULL,
  `sifra_osiguranja` INT NOT NULL,
  `cena` FLOAT(10,2) NOT NULL,
  `sifra_korisnika` INT NOT NULL,
  PRIMARY KEY (`brRegTablica`, `sifra_osiguranja`),
  INDEX `fk_Vozilo_has_Osiguranje_Osiguranje1_idx` (`sifra_osiguranja` ASC),
  INDEX `fk_Vozilo_has_Osiguranje_Vozilo1_idx` (`brRegTablica` ASC),
  INDEX `fk_Poseduje_Osiguranje_Rentira1_idx` (`sifra_korisnika` ASC),
  CONSTRAINT `fk_Vozilo_has_Osiguranje_Vozilo1`
    FOREIGN KEY (`brRegTablica`)
    REFERENCES `mydbrentacar`.`Vozilo` (`brRegTablica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vozilo_has_Osiguranje_Osiguranje1`
    FOREIGN KEY (`sifra_osiguranja`)
    REFERENCES `mydbrentacar`.`Osiguranje` (`sifra_osiguranja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poseduje_Osiguranje_Rentira1`
    FOREIGN KEY (`sifra_korisnika`)
    REFERENCES `mydbrentacar`.`Rentira` (`sifra_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Dodatna_Oprema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Dodatna_Oprema` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Dodatna_Oprema` (
  `sifra_opreme` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `cena` FLOAT(10,2) NOT NULL,
  PRIMARY KEY (`sifra_opreme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbrentacar`.`Rentiranje_opreme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbrentacar`.`Rentiranje_opreme` ;

CREATE TABLE IF NOT EXISTS `mydbrentacar`.`Rentiranje_opreme` (
  `sifra_korisnika` INT NOT NULL,
  `brRegTablica` VARCHAR(10) NOT NULL,
  `sifra_opreme` INT NOT NULL,
  PRIMARY KEY (`sifra_korisnika`, `brRegTablica`, `sifra_opreme`),
  INDEX `fk_Rentira_has_Dodatna_Oprema_Dodatna_Oprema1_idx` (`sifra_opreme` ASC),
  INDEX `fk_Rentira_has_Dodatna_Oprema_Rentira1_idx` (`sifra_korisnika` ASC, `brRegTablica` ASC),
  CONSTRAINT `fk_Rentira_has_Dodatna_Oprema_Rentira1`
    FOREIGN KEY (`sifra_korisnika` , `brRegTablica`)
    REFERENCES `mydbrentacar`.`Rentira` (`sifra_korisnika` , `brRegTablica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rentira_has_Dodatna_Oprema_Dodatna_Oprema1`
    FOREIGN KEY (`sifra_opreme`)
    REFERENCES `mydbrentacar`.`Dodatna_Oprema` (`sifra_opreme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
